from __future__ import annotations

from datetime import UTC, datetime

from pydantic import BaseModel, Field


class PaperMetadata(BaseModel):
    """Raw metadata extracted from a PDF."""
    title: str = "Untitled"
    abstract: str = ""


class ExtractedText(BaseModel):
    """Full text extracted from a PDF."""
    text: str
    metadata: PaperMetadata
    page_count: int


class SummaryResult(BaseModel):
    """Structured summary generated by the AI provider."""
    executive_summary: str
    key_findings: list[str]
    methodology: str
    conclusion: str
    keywords: list[str]


class PaperAnalysis(BaseModel):
    """Complete analysis result for a paper."""
    title: str
    abstract: str
    summary: SummaryResult
    simple_explanation: str = Field(max_length=2000)


class PaperRecord(BaseModel):
    """Database record for a processed paper."""
    id: int | None = None
    filename: str
    title: str
    upload_date: datetime = Field(default_factory=lambda: datetime.now(UTC))
    summary: str = ""
    simple_explanation: str = ""
    keywords: str = ""
    report_path: str = ""
